"""Program files vs. your data, on the real exe.

- WASD_USER_DIR moves everything the exe writes (here: the results page)
  into that folder and leaves the repo alone.
- An installed layout (<install>\\bin\\wasd-cli.exe beside data\\ and
  templates\\, no git checkout) writes to %LOCALAPPDATA%\\WASD and never
  into its own program folder.

Uses a temporary folder with a space and a non-ASCII character in its name.
Windows only; needs build\\wasd-cli.exe (test.ps1 builds it first).
"""
import os
import shutil
import subprocess
import tempfile
import unittest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
EXE = os.path.join(ROOT, "build", "wasd-cli.exe")


def run(args, env_changes, cwd=None):
    env = dict(os.environ)
    for k, v in env_changes.items():
        if v is None:
            env.pop(k, None)
        else:
            env[k] = v
    out = subprocess.run(args, capture_output=True, timeout=60, env=env, cwd=cwd, stdin=subprocess.DEVNULL)
    # `paths` prints UTF-8 (checked strictly there); ordinary log lines use the
    # console code page, so they're decoded leniently.
    strict = len(args) > 1 and args[1] == "paths"
    return (out.returncode, out.stdout.decode("utf-8", "strict" if strict else "replace"),
            out.stderr.decode("utf-8", "replace"))


def parse_paths(text):
    """`wasd-cli.exe paths` output -> {"assets": ..., "user data": ..., "source": ..., "generated": ..., "mode": ...}."""
    out = {}
    for line in text.splitlines():
        key, _, value = line.partition("  ")
        key, value = key.strip(), value.strip()
        if key == "user data":  # "user data  <path>  (<source>)"
            path, _, source = value.rpartition("  (")
            out["user data"], out["source"] = path, source.rstrip(")")
        elif key:
            out[key] = value
    return out


def files_under(folder):
    return sorted(os.path.relpath(os.path.join(d, f), folder) for d, _, fs in os.walk(folder) for f in fs)


@unittest.skipUnless(os.name == "nt" and os.path.exists(EXE), "needs build\\wasd-cli.exe on Windows")
class UserDirOverrideTest(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="wasd paths t\u00e9st ")

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_paths_command_reports_the_override(self):
        code, out, err = run([EXE, "paths"], {"WASD_USER_DIR": self.tmp})
        self.assertEqual(code, 0, err)
        p = parse_paths(out)
        self.assertEqual(p["user data"], self.tmp)
        self.assertEqual(p["source"], "WASD_USER_DIR")
        self.assertEqual(os.path.normcase(p["assets"]), os.path.normcase(ROOT))
        self.assertEqual(p["mode"], "dev checkout")

    def test_report_is_written_into_the_override_not_the_repo(self):
        repo_report = os.path.join(ROOT, "reports", "results.html")
        before = os.path.getmtime(repo_report) if os.path.exists(repo_report) else None
        code, out, err = run([EXE, "report", "--no-open"], {"WASD_USER_DIR": self.tmp})
        self.assertEqual(code, 0, out + err)
        written = os.path.join(self.tmp, "reports", "results.html")
        self.assertTrue(os.path.exists(written), out)
        with open(written, encoding="utf-8") as f:
            self.assertIn("Generated by WASD", f.read())
        after = os.path.getmtime(repo_report) if os.path.exists(repo_report) else None
        self.assertEqual(before, after, "the repo's reports\\results.html was touched")


@unittest.skipUnless(os.name == "nt" and os.path.exists(EXE), "needs build\\wasd-cli.exe on Windows")
class InstalledLayoutTest(unittest.TestCase):
    """The layout the installer will create (installer/wasd.iss), without the installer."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp(prefix="wasd install t\u00e9st ")
        self.app = os.path.join(self.tmp, "Programs", "WASD")
        self.local = os.path.join(self.tmp, "Local")
        os.makedirs(os.path.join(self.app, "bin"))
        os.makedirs(self.local)
        shutil.copy2(EXE, os.path.join(self.app, "bin", "wasd-cli.exe"))
        shutil.copytree(os.path.join(ROOT, "templates"), os.path.join(self.app, "templates"))
        shutil.copytree(os.path.join(ROOT, "data"), os.path.join(self.app, "data"),
                        ignore=shutil.ignore_patterns("generated"))
        self.exe = os.path.join(self.app, "bin", "wasd-cli.exe")
        self.env = {"WASD_USER_DIR": None, "LOCALAPPDATA": self.local}

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def test_paths_resolve_to_the_install_and_localappdata(self):
        code, out, err = run([self.exe, "paths"], self.env)
        self.assertEqual(code, 0, err)
        p = parse_paths(out)
        self.assertEqual(p["mode"], "installed")
        self.assertEqual(p["assets"], self.app)
        self.assertEqual(p["user data"], os.path.join(self.local, "WASD"))
        self.assertEqual(p["source"], "%LOCALAPPDATA%")
        self.assertEqual(p["generated"], os.path.join(self.local, "WASD", "generated"))

    def test_nothing_is_written_into_the_program_folder(self):
        program_files = files_under(self.app)
        # Started from somewhere else, as a shortcut would.
        code, out, err = run([self.exe, "report", "--no-open"], self.env, cwd=self.tmp)
        self.assertEqual(code, 0, out + err)
        self.assertTrue(os.path.exists(os.path.join(self.local, "WASD", "reports", "results.html")), out)
        self.assertEqual(files_under(self.app), program_files)

    def test_finds_its_templates_from_any_working_folder(self):
        code, out, err = run([self.exe, "report", "--no-open"], self.env, cwd=os.environ.get("SystemRoot", "C:\\"))
        self.assertEqual(code, 0, out + err)
        self.assertNotIn("Template missing", out + err)


class ParsePathsTest(unittest.TestCase):
    def test_parse(self):
        p = parse_paths("assets     C:\\A\nuser data  D:\\my data  (WASD_USER_DIR)\ngenerated  C:\\A\\data\\generated\n"
                        "mode       dev checkout\n")
        self.assertEqual(p, {"assets": "C:\\A", "user data": "D:\\my data", "source": "WASD_USER_DIR",
                             "generated": "C:\\A\\data\\generated", "mode": "dev checkout"})


if __name__ == "__main__":
    unittest.main()
