// Version 0.1.0: src/version.h is the one source;
// the results page gets it through BuildReportHtml. The exe's resources
// and the --version output are checked on the built exe by tests/pkg.

TEST(version_macros_agree) {
  std::string joined = std::to_string(WASD_VERSION_MAJOR) + "." + std::to_string(WASD_VERSION_MINOR) + "." +
                       std::to_string(WASD_VERSION_PATCH);
  CHECK_EQ(std::string(WASD_VERSION_STRING), joined);
  CHECK_EQ(std::string(WASD_VERSION_STRING), std::string("0.1.0"));
}

TEST(version_string_is_plain_semver) {
  std::string v = WASD_VERSION_STRING;
  auto parts = SplitStr(v, '.');
  CHECK_EQ(parts.size(), size_t(3));
  for (const auto& p : parts) {
    CHECK(!p.empty() && p.find_first_not_of("0123456789") == std::string::npos);
    CHECK(p == "0" || p[0] != '0');  // no leading zeros
  }
}

TEST(app_identity) {
  CHECK_EQ(std::string(WASD_APP_NAME), std::string("WASD: World Awareness & State Display"));
  CHECK_EQ(std::string(WASD_APP_SHORT_NAME), std::string("WASD"));
  CHECK_EQ(std::string(WASD_APP_PUBLISHER), std::string("AmishGoose"));  // user's choice, 2026-10-07
  CHECK(std::string(WASD_APP_COPYRIGHT).find(WASD_APP_PUBLISHER) != std::string::npos);
}

TEST(report_html_fills_data_and_version) {
  std::string tmpl =
      "<!-- data goes in __SESSIONS_JSON__ below -->\n"
      "<footer>Generated by WASD __APP_VERSION__</footer>\n"
      "<script>const V = \"__APP_VERSION__\"; const SESSIONS = __SESSIONS_JSON__;</script>";
  std::string html = BuildReportHtml(tmpl, "[{\"a\":1}]");
  CHECK(html.find("<!-- data goes in __SESSIONS_JSON__ below -->") != std::string::npos);  // only the last token
  CHECK(html.find("const SESSIONS = [{\"a\":1}];") != std::string::npos);
  CHECK(html.find("Generated by WASD 0.1.0</footer>") != std::string::npos);
  CHECK(html.find("const V = \"0.1.0\"") != std::string::npos);
  CHECK(html.find("__APP_VERSION__") == std::string::npos);
}

TEST(report_html_escapes_script_end_in_data) {
  std::string html = BuildReportHtml("<script>const S = __SESSIONS_JSON__;</script>", "[\"</script><b>\"]");
  CHECK_EQ(html, std::string("<script>const S = [\"<\\/script><b>\"];</script>"));
}

TEST(report_html_leaves_tokens_in_data_alone) {
  // A character literally named "__APP_VERSION__" stays as it is.
  std::string html = BuildReportHtml("v __APP_VERSION__ d __SESSIONS_JSON__", "[\"__APP_VERSION__\"]");
  CHECK_EQ(html, std::string("v 0.1.0 d [\"__APP_VERSION__\"]"));
}

TEST(report_html_needs_the_data_token) {
  CHECK_EQ(BuildReportHtml("<html>no token</html>", "[]"), std::string(""));
  CHECK_EQ(BuildReportHtml("", "[]"), std::string(""));
}

TEST(report_template_has_both_tokens) {
  std::string tmpl = ReadWholeFile(Paths().Template(L"results_template.html"));
  CHECK(tmpl.find("const SESSIONS = __SESSIONS_JSON__;") != std::string::npos);
  CHECK(tmpl.find("<footer>Generated by WASD __APP_VERSION__") != std::string::npos);
}
